name: EC2

on:
  push:
    branches:
      - ec2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy repository to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: '.'
          target: '/home/ec2-user/vizpi_backend'

      - name: Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/vizpi_backend
            npm install
            pm2 stop my-app || true
            pm2 delete my-app || true
            pm2 start app.js --name my-app
